// This file is generated by scripts/generate-graphql-types.ts
// Do not edit this file directly

export type Query =
  | 'getField'
  | 'getFieldValues'
  | 'getFieldValues'
  | 'getProjectField';
export type Mutation = 'clearItemFieldValue' | 'setItemFieldValue';
export type Request = Query | Mutation;

export type ProjectV2FieldValue =
  | {text: string}
  | {number: number}
  | {date: string}
  | {singleSelectOptionId: string}
  | {iterationId: string};

export type RequestParams<T extends Request> = T extends 'getField'
  ? {
      owner: string;
      projectNumber: number;
      fieldName: string;
    }
  : T extends 'getFieldValues'
  ? {
      resourceUrl: string;
    }
  : T extends 'getFieldValues'
  ? {
      resourceUrl: string;
    }
  : T extends 'getProjectField'
  ? {
      owner: string;
      number: number;
    }
  : T extends 'clearItemFieldValue'
  ? {
      projectId: string;
      itemId: string;
      fieldId: string;
    }
  : T extends 'setItemFieldValue'
  ? {
      projectId: string;
      itemId: string;
      fieldId: string;
      value: ProjectV2FieldValue;
    }
  : never;
